-- Initial schema for Pulz durable entities.
-- Hand-authored (not machine-generated by `prisma migrate dev`, since this
-- was scaffolded without a live database connection) to mirror
-- prisma/schema.prisma exactly, plus the CHECK constraint and partial
-- unique index Prisma's schema language can't express natively.
--
-- Once a real DATABASE_URL is available, run `npx prisma migrate deploy`
-- to apply this, or `npx prisma migrate dev` to have Prisma verify it
-- matches the schema and generate any follow-up diff.

-- CreateTable
CREATE TABLE "creators" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "creators_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "quizzes" (
    "id" TEXT NOT NULL,
    "creator_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "cover_image" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "quizzes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "questions" (
    "id" TEXT NOT NULL,
    "quiz_id" TEXT NOT NULL,
    "order" INTEGER NOT NULL,
    "text" TEXT NOT NULL,
    "media_url" TEXT,
    "time_limit_seconds" INTEGER NOT NULL DEFAULT 20,

    CONSTRAINT "questions_pkey" PRIMARY KEY ("id"),
    -- PRD §4.1 / Decision #3: time limit configurable 5-120s.
    -- Belt-and-suspenders: also clamped in the application layer on write.
    CONSTRAINT "questions_time_limit_range" CHECK ("time_limit_seconds" >= 5 AND "time_limit_seconds" <= 120)
);

-- CreateTable
CREATE TABLE "options" (
    "id" TEXT NOT NULL,
    "question_id" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "is_correct" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "options_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "results_snapshots" (
    "session_id" TEXT NOT NULL,
    "generated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "payload" JSONB NOT NULL,

    CONSTRAINT "results_snapshots_pkey" PRIMARY KEY ("session_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "creators_email_key" ON "creators"("email");

-- CreateIndex
CREATE INDEX "quizzes_creator_id_idx" ON "quizzes"("creator_id");

-- CreateIndex
CREATE UNIQUE INDEX "questions_quiz_id_order_key" ON "questions"("quiz_id", "order");

-- CreateIndex
CREATE INDEX "options_question_id_idx" ON "options"("question_id");

-- CreateIndex
-- DESIGN.md §1: "exactly one true per question" is enforced at the
-- application layer on write; this partial unique index is a DB-level
-- backstop that guarantees at most one correct option per question even
-- if the app-layer check is ever bypassed or buggy. It does not by
-- itself guarantee "at least one" -- that half of "exactly one" remains
-- an application-layer responsibility (validated at quiz/question
-- create & update time).
CREATE UNIQUE INDEX "options_one_correct_per_question" ON "options"("question_id") WHERE "is_correct" = true;

-- CreateIndex
CREATE INDEX "results_snapshots_expires_at_idx" ON "results_snapshots"("expires_at");

-- AddForeignKey
ALTER TABLE "quizzes" ADD CONSTRAINT "quizzes_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "creators"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "questions" ADD CONSTRAINT "questions_quiz_id_fkey" FOREIGN KEY ("quiz_id") REFERENCES "quizzes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "options" ADD CONSTRAINT "options_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
